# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [152]:
import numpy as np

np.zeros((100,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
np.ones((100,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [3]:
np.full((100,), 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [4]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [10]:
A = np.identity(5)
A[[1, 0]] = A[[0, 1]]
print(A)

[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 6. Создать вектор со значениями от 10 до 100

In [15]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

#### 7. Развернуть вектор (первый становится последним)

In [19]:
A = np.arange(10)
A = A[::-1]
print (A)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [21]:
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [26]:
A = np.array([1, 2, 3, 4, 5])
B = np.zeros(17)
B[::4] = A
B

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [32]:
np.random.random((3, 3, 3))

array([[[0.04688962, 0.5159868 , 0.39204954],
        [0.08431724, 0.98811445, 0.97185906],
        [0.5150607 , 0.94743284, 0.39414422]],

       [[0.83338143, 0.53979114, 0.57035562],
        [0.98660314, 0.48887159, 0.96836664],
        [0.63660672, 0.97577907, 0.38288249]],

       [[0.10363665, 0.76283678, 0.95806329],
        [0.30553596, 0.00387943, 0.80280254],
        [0.63286352, 0.15858419, 0.83429606]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [8]:
A = np.random.random((10, 10))
print(A.min())
print(A.max())

0.004853540717425275
0.9871708114767621


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [19]:
A = np.random.random((30,))
A.mean()

0.4400540993120644

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [29]:
A = np.ones((3,3))
A[1:-1, 1:-1] = 0
A

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [36]:
np.diag(np.arange(1, 5), - 1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [67]:
A = np.ones((8, 8))
A[::2,1::2] = 0
A[1::2,::2] = 0
A

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [72]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [73]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [78]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [94]:
A = np.arange(50)
A[(A > 3) & (8 >= A)] *= -1
A

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [95]:
A = np.zeros((5, 5))
A += np.arange(5)
A


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

In [111]:
def function():
    for x in range(10):
        yield x
        
A = np.fromiter(function(),dtype=int)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [98]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [120]:
A = np.random.random(10)
A.sort()
A


array([0.07033024, 0.1365142 , 0.29588591, 0.35028229, 0.59465682,
       0.74763143, 0.78918104, 0.8501823 , 0.90801912, 0.95569899])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [126]:
A = np.ones(10)
B = np.zeros(10)

np.allclose(A, B)

False

#### 28. Сделать массив неизменяемым

In [127]:
np.ones(10).flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [129]:
A = np.random.random(100)
n = 10
A[np.argpartition(-A, n)[:n]]

array([0.98822188, 0.98180173, 0.97875262, 0.97833517, 0.96184907,
       0.91467901, 0.86108185, 0.87544928, 0.88648141, 0.90497544])

#### 30. Заменить максимальный элемент на ноль

In [132]:
A = np.random.random(100)
A[A.argmax()] = 0

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [134]:
A = np.zeros((10,10), [('x',float),('y',float)])
A['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
A

array([[(0.        , 0.), (0.11111111, 0.), (0.22222222, 0.),
        (0.33333333, 0.), (0.44444444, 0.), (0.55555556, 0.),
        (0.66666667, 0.), (0.77777778, 0.), (0.88888889, 0.),
        (1.        , 0.)],
       [(0.        , 0.), (0.11111111, 0.), (0.22222222, 0.),
        (0.33333333, 0.), (0.44444444, 0.), (0.55555556, 0.),
        (0.66666667, 0.), (0.77777778, 0.), (0.88888889, 0.),
        (1.        , 0.)],
       [(0.        , 0.), (0.11111111, 0.), (0.22222222, 0.),
        (0.33333333, 0.), (0.44444444, 0.), (0.55555556, 0.),
        (0.66666667, 0.), (0.77777778, 0.), (0.88888889, 0.),
        (1.        , 0.)],
       [(0.        , 0.), (0.11111111, 0.), (0.22222222, 0.),
        (0.33333333, 0.), (0.44444444, 0.), (0.55555556, 0.),
        (0.66666667, 0.), (0.77777778, 0.), (0.88888889, 0.),
        (1.        , 0.)],
       [(0.        , 0.), (0.11111111, 0.), (0.22222222, 0.),
        (0.33333333, 0.), (0.44444444, 0.), (0.55555556, 0.),
        (0.66666667, 0.)

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [136]:
A = np.arange(8)
B = A + 0.5
C = 1.0 / np.subtract.outer(A, B)
print(np.linalg.det(C))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [139]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [144]:
np.random.random((10,10))

array([[0.333, 0.514, 0.025, 0.358, 0.555, 0.375, 0.472, 0.104, 0.687,
        0.383],
       [0.739, 0.496, 0.321, 0.346, 0.418, 0.665, 0.298, 0.786, 0.282,
        0.71 ],
       [0.678, 0.089, 0.737, 0.404, 0.921, 0.144, 0.874, 0.885, 0.566,
        0.548],
       [0.511, 0.022, 0.464, 0.635, 0.064, 0.913, 0.707, 0.006, 0.121,
        0.519],
       [0.829, 0.342, 0.961, 0.251, 0.821, 0.605, 0.372, 0.837, 0.694,
        0.79 ],
       [0.961, 0.06 , 0.382, 0.855, 0.265, 0.11 , 0.723, 0.664, 0.441,
        0.31 ],
       [0.135, 0.951, 0.905, 0.439, 0.425, 0.729, 0.819, 0.136, 0.624,
        0.095],
       [0.01 , 0.043, 0.938, 0.635, 0.107, 0.72 , 0.097, 0.724, 0.509,
        0.652],
       [0.835, 0.23 , 0.22 , 0.748, 0.173, 0.349, 0.229, 0.615, 0.957,
        0.583],
       [0.388, 0.782, 0.679, 0.287, 0.948, 0.845, 0.368, 0.513, 0.105,
        0.183]])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
a = np.arange(10)
n = 5
i = (np.abs(a-n)).argmin()
print(a[i])

#### 36. Преобразовать массив из float в int

In [147]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [148]:
A = np.arange(10)
for index, value in np.ndenumerate(A):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9


#### 38. Случайно расположить p элементов в 2D массив

In [156]:
p = 3
A = np.zeros((5,5))
np.put(A, np.random.choice(range(5*5), p, replace=False), 1)
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 39. Отнять среднее из каждой строки в матрице

In [157]:
A = np.arange(16).reshape(4,4)
B = A - A.mean(axis=1)
B

array([[ -1.5,  -4.5,  -7.5, -10.5],
       [  2.5,  -0.5,  -3.5,  -6.5],
       [  6.5,   3.5,   0.5,  -2.5],
       [ 10.5,   7.5,   4.5,   1.5]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [162]:
A = np.random.randint(0, 16, (4,4))
n=2
print(A[A[:,n].argsort()])

[[10  6  5 12]
 [ 6  2  7  3]
 [ 1 11 14  0]
 [11  0 15 12]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [163]:
A = np.random.randint(0, 16, (4,4))
print((~A.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [171]:
A = np.ones(4)
B = np.random.randint(0, len(A), 4)
A += np.bincount(B, minlength=len(A))
print(A)

[1. 2. 3. 2.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [173]:
w,h = 10,10
A = np.random.randint(0, 2, (w,h,3)).astype(np.ubyte)
B = A[..., 0] * 256 * 256 + A[..., 1] * 256 + A[..., 2]
n = len(np.unique(B))
print(n)

4


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [177]:
A = np.random.randint(0,10, (5,5,5,5))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[107 118  93 103  96]
 [126 104 147  92 121]
 [ 89 126 107 103 120]
 [105 115 103  93 117]
 [127 110  88 109 124]]
