## Практическое задание

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__РЕШЕНИЕ__

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4\\
\end{matrix}
\end{pmatrix}\Leftrightarrow \begin{pmatrix}
\left.\begin{matrix}
1 & 0 & 0 & 3\\ 
0 & 1 & 0 & -6.5\\ 
0 & 0 & 1 & -1.5
\end{matrix}\right|
\begin{matrix}
-2\\ 
0\\
-2\\
\end{matrix}
\end{pmatrix}\Leftrightarrow\begin{cases}
x_{1}=-2-3x_4 \\
x_{2}=6.5x_4 \\
x_{3}=1.5x_4-2
\end{cases}$$

СЛАУ имеет бесконечное кол-во решение указанного вида

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}\leftrightarrow\begin{cases}
x_{1}=1, \\
x_{3}=3, \\
x_{2}=2;
\end{cases}$

СЛАУ совместимая с одним решением

In [4]:
import numpy as np
A = np.array([[3,-1,1],[2,-5, -3],[1,1,-1]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[3,-1,1,4],[2,-5, -3,-17],[1,1,-1,0]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))

Ранг матрицы коэфициентов: 3
Ранг расширенной матрицы: 3


б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}\leftrightarrow \begin{cases}
0=5, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
0=11;
\end{cases}$

СЛАУ несовместимая и не имеет решений

In [5]:
A = np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[2,-4,6,1],[1,-2,3,-2],[3,-6,9,5]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))

Ранг матрицы коэфициентов: 1
Ранг расширенной матрицы: 2


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases} \leftrightarrow\begin{cases}
5x_{1} = 21x_3 - 8, \\
5x_{2} = 14 - 23x_3 
\end{cases}$

СЛАУ совместимая с бесконечным кол-вом решений

In [6]:
A = np.array([[1,2,5],[3,1,-8]])
print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
A_ = np.array([[1,2,5,4],[3,1,-8,-2]])
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))

Ранг матрицы коэфициентов: 2
Ранг расширенной матрицы: 2


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$


In [7]:
A = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])

A_ = np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])

print("Ранг матрицы коэфициентов:", np.linalg.matrix_rank(A))
print("Ранг расширенной матрицы:", np.linalg.matrix_rank(A_))
print("Согласно Теореме Кронекера — Капелли система совместима и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных")

Ранг матрицы коэфициентов: 4
Ранг расширенной матрицы: 4
Согласно Теореме Кронекера — Капелли система совместима и имеет одно решение так как ранг матрицы коэфициентов и расширеной матрицы совпадают и равны числу неизвестных


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

В случае если равенство

$c = 2b - a$

не выполняется, система является не совместной

__5.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [8]:
A = np.array([[1,-2],[3,-4]])
A1 = np.array([[1,-2],[7,-4]])
A2 = np.array([[1,1],[3,7]])
print(f'х1 = {np.linalg.det(A1)/np.linalg.det(A):.0f}')
print(f'х2 = {np.linalg.det(A2)/np.linalg.det(A):.0f}')

х1 = 5
х2 = 2


 __6.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

  $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

In [14]:
from scipy.linalg import lu
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = lu(A)
B = P.dot(L).dot(U)
print('B:')
print(B)
print('L:')
print(L)

B:
[[ 1.  2.  4.]
 [ 2.  9. 12.]
 [ 3. 26. 30.]]
L:
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]


__7.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__8.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [15]:
from numpy.linalg import cholesky
# define a 3x3 matrix
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
# Cholesky decomposition
L = cholesky(A)
print(L)

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


In [16]:
LT = L.T
print(LT)

[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]


$Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=\frac{5\cdot 59 - 460}{5} = -33,$$

$$y_{3}=\frac{193 - 5 \cdot 59 -2 \cdot (-33)}{3}=-12.$$

$L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=\frac{-33+8}{5} = -5$$

$$x_{1}=\frac{59-25+20}{9}=6.$$

9. 1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [20]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [21]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [22]:
print(f'D:\n{D}')
print(f'U:\n{U}')
print(f'V:\n{V}')

D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
