## Практическое задание

In [1]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   
   
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - неопределена; $BA$ - $2\times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $3\times 3$; $BA$ - $8\times 8$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)

In [8]:
A = np.array([[1, 2], [3, 4],[5, 6], [7, 8]])
B = np.array([[-1, -2], [-3, -4], [-5 ,-6], [-7, -8]])
print(f'AB\n{np.dot(A, B)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [9]:
print(f'AB\n{np.dot(B, A)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

 б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - неопределена; $BA$ - $2\times 3$

In [11]:
A = np.array([[1, 1, 2, 2, 3], [4, 4, 5, 5, 3]])
B = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9], [11, 12, 13], [14, 15, 16]])

print(f'AB\n{np.dot(A, B)}')

AB
[[ 83  92 101]
 [152 173 194]]


In [12]:
print(f'BA\n{np.dot(B, A)}')

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $3\times 3$; $BA$ - $8\times 8$

In [14]:
A = np.array([[3, 4, 2], [11, 0, 4], [5 ,7, -2], [5, 7, -2], [1 ,-1, 1], [3 ,-4, 5], [9 ,1, 3], [11,-12, 0]])
B = np.array([[1, 1, 1, 8, 8, 8, 6, 5], [1, 9, 12, -5, 6, 7, 8, -9], [1, 2, 8, 0, 0, -4, 9, 8]])
print(f'AB\n{np.dot(A, B)}')

AB
[[   9   43   67    4   48   44   68   -5]
 [  15   19   43   88   88   72  102   87]
 [  10   64   73    5   82   97   68  -54]
 [  10   64   73    5   82   97   68  -54]
 [   1   -6   -3   13    2   -3    7   22]
 [   4  -23   -5   44    0  -24   31   91]
 [  13   24   45   67   78   67   89   60]
 [  -1  -97 -133  148   16    4  -30  163]]


In [15]:
print(f'AB\n{np.dot(B, A)}')

AB
[[200 -27  54]
 [137 135  89]
 [222 -11   1]]


   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

In [16]:
A = np.array([[1, 2, 3, 4], [4, 3, 2, 1], [0, 11, 12, 3], [4, 5, 6, 7]])
B = np.array([[2, 3, 2, 3], [12, 1, 7, 6], [3, 2, 2, 0], [-6, -7, -8, -9]])
print(f'AB\n{np.dot(A, B)}')

AB
[[ 11 -17 -10 -21]
 [ 44  12  25  21]
 [150  14  77  39]
 [ 44 -20  -1 -21]]


In [17]:
print(f'AB\n{np.dot(B, A)}')

AB
[[  26   50   54   38]
 [  40  134  158  112]
 [  11   34   37   20]
 [ -70 -166 -182 -118]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

In [18]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

Сумма

In [20]:
print(A + B)

[[ 5 -3]
 [ 3  5]]


Произведение

In [19]:
print(f'AB\n{np.dot(A, B)}')

AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [32]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2 ,-1]])
C = np.array([[2 ,-4],[1, 1]])

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{A*3+(-2)*B+4*C}")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [34]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
print(np.dot(A, At))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [36]:
print(np.dot(At, A))

[[45  0]
 [ 0 14]]



__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [38]:
A = np.array([[np.sin(1), -(np.cos(1))], [np.cos(1), np.sin(1)]])
print(np.linalg.det(A))

1.0


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [39]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(np.linalg.det(A))

180.0


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [44]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
-0


определитель такой матрицы равен 0 т.к если из второй и третьей строки вычесть первую то вторая и третья строки будет линейно зависимыми

__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [46]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(np.linalg.det(A))

0.0


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [47]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(np.linalg.matrix_rank(A))

2
